### ISSUE TITLE
UX: Auto-rounding of hours

### ISSUE THREAD

**Issue by fillerwriter** [phase2/openair-reborn#10]
With the timers, it would be nice if there was a way to round the hours to 15-minute increments automatically.

**Comment by crittermike** [comment]
That actually happens automatically by OpenAir when you save your
timesheet. Does that work for you?

**Comment by fillerwriter** [comment]
When you use the timer to keep track of time, it will leave an unrounded # in the edit page.
![oa-reborn](https://cloud.githubusercontent.com/assets/254626/3706274/9b88de2c-1427-11e4-8b76-fadb6ac0971b.png)

**Comment by crittermike** [comment]
Ah, I see what you mean now. I just broke that yesterday actually--it used
to display them rounded to 3 decimals. I can fix that. Thanks!

**Comment by crittermike** [comment]
Fixed this when editing. That should hopefully fix the UI aspect of it. It will still appear un-rounded in the OpenAIr time grid when you click "preview" until you save (at which point OA itself will round to the nearest quarter hour), but that's a narrow enough edge case that I think it's not worth looking at.
