### ISSUE TITLE
UX: Auto-scroll on edit

### ISSUE THREAD

**Issue by fillerwriter** [phase2/openair-reborn#11]
When you click on the edit icon for a time entry, it's not obvious that you need to scroll to the top to see the edit form, especially on forms that have lots of time entries already. I think this would be best solved by having the page scroll to the top when you click the edit icon.

**Comment by crittermike** [comment]
Ah, very good idea, and easy to implement. Thanks!

**Comment by crittermike** [comment]
Pushed a fix which will be included in the next release.
