### ISSUE TITLE
Day selection widget should present all options

### ISSUE THREAD

**Issue by grayside** [phase2/openair-reborn#14]
Right now the options in selecting a day include focusing on the widget and typing, or focusing on the widget and selecting a day option. However, this is a case where their are finite options. Maybe instead of this, having something more like styled radio buttons would work?

Su M T W Th F Sa

**Comment by crittermike** [comment]
I'm not sure I understand why finite options == not a good use case for
multi-select chosen dropdowns. Can you clarify? I'm worried about styled
radio buttons because I want to ensure that the whole form can be filled
out and submitted without ever using the mouse.

**Comment by crittermike** [comment]
@grayside did you want to reply to this?

**Comment by grayside** [comment]
I think keyboard operation may be legitimately preferred. I bring this up from the use case of mass transcription, where I found the current keyboard ordering to be unhelpful. For transcription purposes:
1. Ensure Day
2. Specify Project & Task
3. Enter Time
4. Enter Action

As a result, mouse becomes necessary to partially invert the navigation.

This will be less of a problem going forward for me, as I am sufficiently delighted by the new interface that I'll be using it as primary time entry from now on.

**Comment by crittermike** [comment]
Gotcha, let me let this stew a bit. There might be a decent way to get the
best of both worlds.

**Comment by crittermike** [comment]
Maybe something like http://fronteed.com/iCheck/ (the checkboxes) which would list all 7 as checkboxes and you could tab through them and hit space to toggle each one as needed? Not immediately sure if that would be a better or worse UI than what we have now. Thoughts?

**Comment by crittermike** [comment]
I'm going to assume that since nobody else has complained about it, it's probably not worth investing a lot of time in.
