### ISSUE TITLE
In Preview some line entries are pushed above the UI view (hidden)

### ISSUE THREAD

**Issue by bhuber2010** [phase2/openair-reborn#8]
![2014-07-24 10_34_43-untitled - paint](https://cloud.githubusercontent.com/assets/4156395/3692608/32594b22-135e-11e4-86ff-e0abf278c1a8.png)

**Comment by crittermike** [comment]
Interesting, I haven't seen this issue yet. Are you able to scroll up to
it? Do you have a very small window or a lot of time entries, i.e., enough
that it can't all be seen without scrolling?

**Comment by bhuber2010** [comment]
Yes its only those two lines as you can see the hours add up to 8 hours each day, just two lines of 4 hrs. It doesn't always happen, but it'd say 50% of the time it does. The window is full screen at 1080p resolution.

**Comment by crittermike** [comment]
Has anyone besides you hit this issue? We're going to be releasing the extension to my company in the next couple days and I can see if any of them run into it too. Unfortunately without being able to reproduce it it's tough for me to debug, so hopefully one of the people at my company will see it and I can dig in.

**Comment by bhuber2010** [comment]
Yes, Marlon and I both have and I am working on figuring out exact repro steps.

**Comment by bhuber2010** [comment]
Ah, It happens after deleting one of the lines in the preview view. It just jumps up when the line is deleted. Or when clicking this pin (twice in a row) it also does it.
![2014-07-24 11_41_12-openair _ timesheets _ adaptive planning](https://cloud.githubusercontent.com/assets/4156395/3692989/2a758dcc-1362-11e4-9fcd-b4520c63113d.png)

**Comment by crittermike** [comment]
Can you give me exact steps to reproduce? Like first click this, then that,
etc. I deleted a few lines in preview and still can't see the problem.

**Comment by bhuber2010** [comment]
1) Click into time sheet with at least a couple rows (I have just 2)
2) Click Preview
3) Click any of the buttons circled in the screenshot (Delete requires second click on popup word to confirm)
4) UI shifts up with each click
![2014-07-25 11_32_47-adaptive officeconnect - 01__summary_report_vs_fy14_forecast_ 28w_variance 29 xl](https://cloud.githubusercontent.com/assets/4156395/3706620/7ca8070e-142b-11e4-9358-9339132109ef.png)
![2014-07-25 11_43_09-openair _ timesheets _ adaptive planning](https://cloud.githubusercontent.com/assets/4156395/3706640/a5053fe6-142b-11e4-8378-2c52d1e96b20.png)

**Comment by crittermike** [comment]
On my end it looks like it's just removing the header line which doesn't really cause any issues. Is that not what's happening for you?

**Comment by crittermike** [comment]
I just pushed 0.0.15 which _should_ fix this stuff. Let me know if it does not.
